### ISSUE TITLE
30/09/15 - Reunião de alinhamento, pós-validação -  18:00 às 20:30

### ISSUE THREAD

**Issue by Micael0706** [Micael0706/qsproject#12]
Reunião com o time, para comemorar a validação e planejar próximas etapas do projeto.

Pauta - Assuntos:
1. Discutir características do Perfil do MEI.
2. Determinar o acompanhamento das tarefas a serem feitas.
3. Aprender funcionalidades do Perfil do MEI.
4. Definir próximos passos a serem dados no projeto.
5. começar a criar o protótipo
.

Att
Micael

**Comment by Micael0706** [comment]
Reunião já foi realizada.

Att
Micael

**Comment by jorgehclinhares** [comment]
Micael, é importante toda reunião ter uma pauta. Poderia disponibilizar?

Em sáb, 3 de out de 2015 3:15 PM, Micael Souza <notifications@github.com>
escreveu:

**Comment by Micael0706** [comment]
Jorge, foi adicionado a pauta nessa tarefa, como pedido.

Att
Micael
