### ISSUE TITLE
readme/inicial com nome do projeto, suas características, time e demais informações pertinentes;

### ISSUE THREAD

**Issue by Micael0706** [Micael0706/qsproject#6]
Preencher o repositório público inicial GitHub para o seu projeto -- página de readme/inicial com nome do projeto, suas características, time e demais informações pertinentes;

**Comment by Micael0706** [comment]
Nova tarefa.

Para conhecimento.

**Comment by Micael0706** [comment]
Emmerson, segue atividade.

**Comment by Micael0706** [comment]
Julio Alexandre, segue atividade, favor verificar.

**Comment by oseildo** [comment]
Ainda esta atribuída a mim?

**Comment by oseildo** [comment]
Foi mal, li o restante agora...

**Comment by japm94** [comment]
Em estado de aprovação
